version: '2'
services:
  postgresdata:
    image: "postgres"
    container_name: postgresdata
    volumes:
      - /vagrant/postgres/data:/data
    command: /bin/true
    
  postgresdb:
    build: ./postgres
    image: "harshal-shah/mypostgres:1.3"
    container_name: postgresdb
    volumes_from:
      - postgresdata
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
  pgwriter:
    build: ./postgreswriter
    image: "harshal-shah/postgreswriter:1.1"
    container_name: "pgwriter"
    links:
      - "postgresdb:postgres"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
      - POSTGRES_TABLE=flockertab
      - POSTGRES_HOST=postgres
  web:
    container_name: "web"
    restart: always
    build: ./web
    image: "harshal-shah/web"
    expose:
      - "8000"
    links:
      - "postgresdb:postgres"
    volumes:
      - /vagrant/web/static:/usr/src/app/static
    env_file: ./config/.env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    container_name: "ngnix"
    restart: always
    build: ./nginx/
    image: "harshal-shah/nginx"
    ports:
      - "80:80"
    volumes:
      - /vagrant/web/static:/www/static
    volumes_from:
      - web
    links:
      - web:web


